### ISSUE TITLE
Calrification on the HW connections

### ISSUE THREAD

**Issue by schneemaier** [muxa/esphome-micron-alarm#1]
Hello, I just found your repository and I have an alarm from the same company (MICRON), though it is a different version .

I am thinking on trying out this config, but it is not clear how the ESP Home device conncets to the keypad. There are 3 ppins in the config:
-  clock_pin: number: D1
-  data_in_pin: number: D2
-  data_out_pin: D5
D1 and D2 seems to be clear: tap on the wires going to the keyboard, but how should I connect D5 ? 

A simple wiring diagram would be very useful!

Thank you

**Comment by muxa** [comment]
Hi @schneemaier 

Here's is the schematic. Hope you find it useful!
[Schematic_Micron Lynx Alarm_2022-09-12.pdf](https://github.com/user-attachments/files/17103792/Schematic_Micron.Lynx.Alarm_2022-09-12.pdf)

**Comment by muxa** [comment]
I've also updated the README with the schematic.

**Comment by schneemaier** [comment]
Thank you! This is exaclty what I was looking for!

**Comment by muxa** [comment]
I've also added example config, as there's more to getting the alarm to work as alarm in HA than this integration.
